name: oregonate
on:
  push:
    branches: [ main ]
jobs:
  container-oregantor-job:
    runs-on: ubuntu-latest
    container:
      image: dolfinx/dolfinx:stable
    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Run simulation
        run: mpirun -np ${{ steps.cpu-cores.outputs.count }} python3 oregonator.py
        
      - name: Package Results
        run: tar --create --gzip --file oregonator_output.tar.gz oreg_output.xdmf oreg_output.h5
        
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with: 
          name: oregonator_output.tar.gz
          if-no-files-found: error
          path: oregonator_output.tar.gz
